# Generated by Django 6.1 on 2026-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author__isnull', False), ('publisher__isnull', True)), models.Q(('author__isnull', True), ('publisher__isnull', False)), _connector='OR'), name='article_has_one_source'),
        ),
    ]
